# Run BEHAV3D feature extraction and T cell analysis

**Expected duration full processing per full time-series BEHAV3D position: ~4-5 hours**

This notebook runs the feature extraction and behavioral analysis pipeline of BEHAV3D

To work correctly, it requires the following input:
- A metadata ***.csv*** containing information on every sample to be processed
- A 5D (tczyx) microscopy image (***.czi/.tiff/.zarr***)

*Optional*: You can supply your own segmentation/tracking in the metadata .csv and skip the segmentation/tracking by BEHAV3D

### Load required packages

In [1]:
#Load the packages
from behav3d.preprocessing.segmentation.unet_segmentation import run_behav3d_unet_segmentation
from behav3d.preprocessing.segmentation.napari_pixelclassifier import train_pixel_classifier, run_pixel_classifier_segmentation
from behav3d.preprocessing.tracking.laptracking import run_tcell_laptracking
from behav3d.preprocessing.tracking.propagation_tracking import run_propagation_tracking
from behav3d.utils.tracking import convert_all_tracked_images_to_csv

from behav3d.analysis.feature_extraction import run_feature_extraction
from behav3d.analysis.tcell_analysis import filter_tcell_tracks, summarize_track_features, run_tcell_analysis
from behav3d.analysis.organoid_analysis import filter_organoid_tracks, run_organoid_analysis
from behav3d.analysis.backprojection import backproject_mean_features_behav3d

from behav3d.utils import load_behav3d_metadata, check_behav3d_metadata

import pandas as pd
from pathlib import Path

import torch
import zarr
import dask.array as da
import tqdm

import ipywidgets as widgets
from IPython.display import display, clear_output

import random
random.seed(42)  # sets the seed for the random module

import numpy as np
np.random.seed(42)  # sets the seed for numpy random functions


%matplotlib inline

### Set BEHAV3D parameters

***NOTE*** 

Dynamic Time Warping seems to work best if all tracks are of equal length. To get tracks to equal length, set both ***tcell_min_track_length*** and ***tcell_max_track_length*** to the same value

**!!! Make sure channel indexing in metadata csv starts at channel 0!!!**

Checks the supplied metadata .csv for:
- Are all required columns filled in?
- Do all the supplied paths per row exist?

In [2]:
# Path widgets only
output_dir_widget = widgets.Text(
    value=r"D:/SURF_2/Scripts/Python/BEHAV3D3_0/output",
    description='Output Dir:', style={'description_width': '70px'},
    layout=widgets.Layout(width='100%')
)

metadata_path_widget = widgets.Text(
    value=r"D:/SURF_2/Scripts/Python/BEHAV3D3_0/metadata.csv",
    description='Metadata:',
    layout=widgets.Layout(width='100%')
)

load_button = widgets.Button(description="Load Metadata", button_style='success')
output_area = widgets.Output()

def on_load_clicked(b):
    global output_dir, metadata_csv_path, metadata
    output_dir = output_dir_widget.value
    metadata_csv_path = metadata_path_widget.value
    
    with output_area:
        clear_output()
        print(f"Loading metadata from:\nOutput Dir: {output_dir}\nMetadata CSV: {metadata_csv_path}")
        metadata = load_behav3d_metadata(metadata_csv_path)
        display(metadata)
        print("Checking metadata...")
        check_behav3d_metadata(metadata)
        print("✅ Metadata checks passed!")

load_button.on_click(on_load_clicked)

display(output_dir_widget, metadata_path_widget, load_button, output_area)

Text(value='D:/SURF_2/Scripts/Python/BEHAV3D3_0/output', description='Output Dir:', layout=Layout(width='100%'…

Text(value='D:/SURF_2/Scripts/Python/BEHAV3D3_0/metadata.csv', description='Metadata:', layout=Layout(width='1…

Button(button_style='success', description='Load Metadata', style=ButtonStyle())

Output()

---

# Preprocessing of input images for BEHAV3D processing

---

### Segment all input images
*Expected duration: ~3.5 hours per image, ~20 seconds per timepoint*,

In [3]:
train_pixel_classifier(
    output_dir,
    metadata,
    examples_per_sample = 3,
    n_workers=16
    )

Loading existing user labelled organoid data
Loading existing user labelled Tcell data
Loading existing user labelled dead data

In [3]:
print("######## Running segmentation of Organoids and T-cells (Organoid tracking included in segmentation step)", flush=True)
metadata = run_pixel_classifier_segmentation(
    metadata = metadata, 
    output_dir=output_dir,
    organoid_edt_threshold=12,
    timepoint_range=(0, 4)  # This will process timepoints 0, 1, 2, 3, 4

    )

print("\n!!! Overwriting 'tcell_segments_image_path' and 'organoid_segments_image_path' in metadata.csv", flush=True)
metadata.to_csv(metadata_csv_path, sep=",", index=False)

######## Running segmentation of Organoids and T-cells (Organoid tracking included in segmentation step)
Processing sample: FUNC_BV1_Exp059_Img005_e
(600, 4, 40, 256, 256)
Already segmented, skipping

!!! Overwriting 'tcell_segments_image_path' and 'organoid_segments_image_path' in metadata.csv

### Track all T cells images & Organoid

In [4]:
print("######## Running tracking on T-cells")
metadata = run_tcell_laptracking(
    metadata = metadata, 
    output_dir=output_dir,
    overwrite=False,
    cell_type="tcell",
    logger=None
    )
print("\n!!! Overwriting 'tcell_tracks_image_path' and 'tcell_tracks_csv_path' in metadata.csv")
metadata.to_csv(metadata_csv_path, sep=",", index=False)

print("######## Running tracking on organoids")
metadata = run_propagation_tracking(
    metadata = metadata,
    output_dir = output_dir,
    cell_type="organoid",
    overwrite=True,
    )
print("\n!!! Overwriting 'organoid_tracks_csv_path' in metadata.csv")
metadata.to_csv(metadata_csv_path, sep=",", index=False)

######## Running tracking on T-cells
Tracking sample: FUNC_BV1_Exp059_Img005_e
Tracking already exists... Provide overwrite=True to overwrite... Loading existing tracking data

!!! Overwriting 'tcell_tracks_image_path' and 'tcell_tracks_csv_path' in metadata.csv
######## Running tracking on organoids
Tracking sample: FUNC_BV1_Exp059_Img005_e

100%|██████████| 5/5 [00:01<00:00,  4.01it/s]
100%|██████████| 5/5 [00:00<00:00, 19.42it/s]

!!! Overwriting 'organoid_tracks_csv_path' in metadata.csv

---

# Calculate the track features, filter tracks and summarize track features

---

**calculate_track_features** <br>
Calculates movement, contact and intensity features for each timepoint in all tracks per experiment

**filter_tracks** <br>
Filter out tracks based on:
- Maximum experiment length (tcell_exp_duration)    
- Minimum track length (tcell_min_track_length)
- Tracks starting at timepoint 1 with a dead dye mean over the dead_dye_threshold (dead_dye_threshold)

Additonally, all tracks are cut down to:
- Maximum track length (tcell_max_track_length)

**summarize_track_features** <br>
Summarizes the features into one value for each TrackID per experiment

--------------------

## T cells

**Calculation of track features**

*Expected duration: ~30 minutes*

In [5]:
run_feature_extraction(
    dead_mask_percentage_threshold=0.2,
    metadata=metadata, 
    output_dir=output_dir, 
    cell_type="tcell",
    n_workers=16
    )

--------------- Processing tcell: FUNC_BV1_Exp059_Img005_e ---------------
###### Running track feature calculation
20:08:12 - Converting all input files to .zarr for memory efficiency...
Skipping conversion of tcell segments to zarr, as file already exists
Skipping conversion of organoid segments to zarr, as file already exists
Skipping conversion of raw_image to zarr, as file already exists
20:08:12 - Loading in tracks csv...
20:08:12 - Generalizing the units of position and time to um and hours
20:08:12 - Converting distance and time unit to default um and hours...
20:08:12 - Calculating single-timepoint image-based features...
20:08:12 - Calculating morphology features...
Morphology calculation .csv already exists. Loading in intensity information...
20:08:12 - Calculating channel and especially death dye intensities...
Intensity calculation .csv already exists. Loading in intensity information...
20:08:12 - Calculating number of dead mask pixels...
Dead mask calculation .csv already exists. Loading in intensity information...

D:\SURF_2\Scripts\Python\BEHAV3D3_0\behav3dMA\behav3d\analysis\feature_extraction.py:540: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_tracks = df_tracks.groupby('TrackID').apply(calculate_relative_time).reset_index(drop=True)

20:08:12 - Calculating contact with organoids and other T cells...
Using a contact threshold of 3.6 um
Contact .csv already exists. Loading in contact information...
20:08:12 - Interpolating missing timepoints based on time interval
20:08:14 - Calculating movement features...
20:08:14 - Calculating T-cell specific features...
20:08:14 - Calculating cell death based on defined dead_dye_threshold 0.2
20:08:14 - Determining active contact of T cells
20:08:14 - Perform z-normalization on selected feature columns
20:08:14 - Writing output to D:\SURF_2\Scripts\Python\BEHAV3D3_0\output\trackdata\FUNC_BV1_Exp059_Img005_e\tcell\FUNC_BV1_Exp059_Img005_e_tcell_track_features.csv
###### DONE - elapsed time: 0:00:02

,TrackID,position_t,SegmentID,position_x,position_y,position_z,pixel_position_x,pixel_position_y,pixel_position_z,relative_time,...,displacement_from_origin,mean_square_displacement,speed,mean_speed,dead,active_tcell_contact,z_mean_square_displacement,z_speed,z_mean_dead_dye,sample_name
0,1,0.0,1.0,161.357563,86.690336,9.539160,91.162465,48.977591,5.389356,1.0,...,0.000000,0.000000,0.000000,0.000000,False,False,-0.490680,-0.641942,-1.274452,FUNC_BV1_Exp059_Img005_e
1,1,1.0,1.0,161.327554,87.179350,9.699381,91.145511,49.253870,5.479876,2.0,...,0.515467,0.132853,1.546400,1.546400,False,False,-0.490123,-0.583757,-1.304188,FUNC_BV1_Exp059_Img005_e
2,1,2.0,1.0,160.267326,87.542965,9.786453,90.546512,49.459302,5.529070,3.0,...,1.405969,1.080210,3.372676,2.459538,False,False,-0.486152,-0.515042,-1.407670,FUNC_BV1_Exp059_Img005_e
3,1,3.0,1.0,160.404220,87.390367,9.900092,90.623853,49.373089,5.593272,4.0,...,1.236599,0.630369,0.703178,1.874085,False,False,-0.488038,-0.615484,-1.396889,FUNC_BV1_Exp059_Img005_e
4,1,4.0,1.0,160.192234,88.548229,9.660245,90.504087,50.027248,5.457766,5.0,...,2.196456,2.092792,3.603884,2.306534,False,False,-0.481907,-0.506342,-1.398618,FUNC_BV1_Exp059_Img005_e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,203,4.0,192.0,301.018000,417.484000,16.638000,170.066667,235.866667,9.400000,1.0,...,0.000000,0.000000,0.000000,0.000000,False,False,-0.490680,-0.641942,-0.612944,FUNC_BV1_Exp059_Img005_e
916,204,4.0,194.0,241.122273,450.384545,16.251818,136.227273,254.454545,9.181818,1.0,...,0.000000,0.000000,0.000000,0.000000,False,False,-0.490680,-0.641942,-0.900811,FUNC_BV1_Exp059_Img005_e
917,205,4.0,224.0,217.021667,397.856667,40.587083,122.611111,224.777778,22.930556,1.0,...,0.000000,0.000000,0.000000,0.000000,False,False,-0.490680,-0.641942,-0.696570,FUNC_BV1_Exp059_Img005_e
918,206,4.0,352.0,274.077692,397.296923,32.813077,154.846154,224.461538,18.538462,1.0,...,0.000000,0.000000,0.000000,0.000000,False,False,-0.490680,-0.641942,0.293098,FUNC_BV1_Exp059_Img005_e
919,207,4.0,360.0,317.102308,433.513846,37.306154,179.153846,244.923077,21.076923,1.0,...,0.000000,0.000000,0.000000,0.000000,False,False,-0.490680,-0.641942,0.242391,FUNC_BV1_Exp059_Img005_e

## Organoids

In [6]:
run_feature_extraction(
    metadata=metadata, 
    output_dir=output_dir, 
    cell_type="organoid",
    n_workers=16
    )

--------------- Processing organoid: FUNC_BV1_Exp059_Img005_e ---------------
###### Running track feature calculation
20:08:20 - Converting all input files to .zarr for memory efficiency...
Skipping conversion of tcell segments to zarr, as file already exists
Skipping conversion of organoid segments to zarr, as file already exists
Skipping conversion of raw_image to zarr, as file already exists
20:08:20 - Loading in tracks csv...
20:08:20 - Generalizing the units of position and time to um and hours
20:08:20 - Converting distance and time unit to default um and hours...
20:08:20 - Calculating single-timepoint image-based features...
20:08:20 - Calculating morphology features...
Morphology calculation .csv already exists. Loading in intensity information...
20:08:20 - Calculating channel and especially death dye intensities...
Intensity calculation .csv already exists. Loading in intensity information...
20:08:20 - Calculating number of dead mask pixels...
Dead mask calculation .csv already exists. Loading in intensity information...
20:08:20 - Calculating contact with organoids and other T cells...
Using a contact threshold of 3.6 um
Contact .csv already exists. Loading in contact information...
20:08:20 - Interpolating missing timepoints based on time interval

D:\SURF_2\Scripts\Python\BEHAV3D3_0\behav3dMA\behav3d\analysis\feature_extraction.py:540: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_tracks = df_tracks.groupby('TrackID').apply(calculate_relative_time).reset_index(drop=True)

20:08:20 - Calculating movement features...
20:08:20 - Calculating organoid specific features...
20:08:20 - Perform z-normalization on selected feature columns
20:08:20 - Writing output to D:\SURF_2\Scripts\Python\BEHAV3D3_0\output\trackdata\FUNC_BV1_Exp059_Img005_e\organoid\FUNC_BV1_Exp059_Img005_e_organoid_track_features.csv
###### DONE - elapsed time: 0:00:00

,TrackID,SegmentID,position_t,position_x,position_y,position_z,pixel_position_x,pixel_position_y,pixel_position_z,relative_time,...,displacement,cumulative_displacement,displacement_from_origin,mean_square_displacement,speed,mean_speed,z_mean_square_displacement,z_speed,z_mean_dead_dye,sample_name
0,1,1.0,0.0,342.212428,227.035323,39.206547,193.340355,128.268544,22.150592,1.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.272931,-0.539854,0.282229,FUNC_BV1_Exp059_Img005_e
1,1,1.0,1.0,342.185206,227.428755,39.328650,193.324975,128.490822,22.219576,2.0,...,0.412842,0.412842,0.412842,0.085219,1.238527,1.238527,-0.269823,-0.391166,0.279969,FUNC_BV1_Exp059_Img005_e
2,1,1.0,2.0,342.414845,227.162387,39.015235,193.454715,128.340331,22.042506,3.0,...,0.471079,0.883921,0.306134,0.105211,1.413236,1.325881,-0.269094,-0.370191,0.277261,FUNC_BV1_Exp059_Img005_e
3,1,1.0,3.0,342.629943,226.960530,38.924859,193.576239,128.226288,21.991446,4.0,...,0.308515,1.192435,0.509177,0.233629,0.925544,1.192435,-0.264410,-0.428740,0.276236,FUNC_BV1_Exp059_Img005_e
4,1,1.0,4.0,342.448537,227.225422,38.857979,193.473750,128.375945,21.953661,5.0,...,0.327947,1.520382,0.461936,0.136598,0.983840,1.140287,-0.267949,-0.421741,0.294871,FUNC_BV1_Exp059_Img005_e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,45,45.0,0.0,226.964678,238.879460,62.178327,128.228631,134.960147,35.128998,1.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.272931,-0.539854,0.710091,FUNC_BV1_Exp059_Img005_e
219,45,45.0,1.0,226.827276,239.435021,62.268675,128.151003,135.274023,35.180042,2.0,...,0.579388,0.579388,0.579388,0.167845,1.738163,1.738163,-0.266809,-0.331183,0.717462,FUNC_BV1_Exp059_Img005_e
220,45,45.0,2.0,226.993964,238.743350,61.875426,128.245178,134.883249,34.957868,3.0,...,0.812919,1.392307,0.333365,0.257324,2.438758,2.088461,-0.263546,-0.247075,0.753196,FUNC_BV1_Exp059_Img005_e
221,45,45.0,3.0,226.604500,237.965557,61.972704,128.025141,134.443817,35.012827,4.0,...,0.875276,2.267584,1.003607,1.017472,2.625829,2.267584,-0.235821,-0.224616,0.737760,FUNC_BV1_Exp059_Img005_e
222,45,45.0,4.0,226.795710,238.248958,61.618614,128.133170,134.603931,34.812776,5.0,...,0.492196,2.759780,0.859861,0.632324,1.476589,2.069835,-0.249869,-0.362586,0.782074,FUNC_BV1_Exp059_Img005_e

---

# Perform data analysis

---

## T cell behavioral analysis

**Filtering tracks and summarizing features**

*Expected duration: <1 minute*

### Filtering Parameters 

- **exp_duration**  
  Maximum length of the experiment in timepoints.  
  All data points after this timepoint will be excluded.  
  *Use this to remove late timepoints where imaging quality may degrade significantly.*

- **tcell_min_track_length**  
  Minimum track length to include in the analysis.  
  *Tracks shorter than this are filtered out, typically removing segmentation or tracking errors.*

- **tcell_max_track_length**  
  Maximum track length to include in the analysis.  
  *Longer tracks will be truncated to this length to ensure comparability across tracks of equal length.*

In [7]:

# Widgets for parameters
exp_duration_widget = widgets.IntText(
    value=1000,  # or your default experiment duration
    description='Exp Duration:',
    style={'description_width': '110px'},
    layout=widgets.Layout(width='300px')
)

min_track_length_widget = widgets.IntSlider(
    value=100, min=0, max=1000, step=1,
    description='Min Track Length:',
    style={'description_width': '130px'},
    layout=widgets.Layout(width='300px')
)

max_track_length_widget = widgets.IntSlider(
    value=500, min=0, max=1000, step=1,
    description='Max Track Length:',
    style={'description_width': '130px'},
    layout=widgets.Layout(width='300px')
)

set_params_button = widgets.Button(description="Set Parameters", button_style='info')
output_area_params = widgets.Output()

def on_set_params_clicked(b):
    global exp_duration, tcell_min_track_length, tcell_max_track_length
    exp_duration = exp_duration_widget.value
    tcell_min_track_length = min_track_length_widget.value
    tcell_max_track_length = max_track_length_widget.value
    
    with output_area_params:
        clear_output()
        print(f"Parameters set:")
        print(f"  Experiment Duration: {exp_duration}")
        print(f"  Min Track Length: {tcell_min_track_length}")
        print(f"  Max Track Length: {tcell_max_track_length}")

set_params_button.on_click(on_set_params_clicked)

display(exp_duration_widget)
display(min_track_length_widget, max_track_length_widget)
display(set_params_button, output_area_params)

IntText(value=1000, description='Exp Duration:', layout=Layout(width='300px'), style=DescriptionStyle(descript…

IntSlider(value=100, description='Min Track Length:', layout=Layout(width='300px'), max=1000, style=SliderStyl…

IntSlider(value=500, description='Max Track Length:', layout=Layout(width='300px'), max=1000, style=SliderStyl…

Button(button_style='info', description='Set Parameters', style=ButtonStyle())

Output()

In [14]:
df_tracks_filt = filter_tcell_tracks(
    metadata=metadata, 
    output_dir=output_dir, 
    exp_duration=exp_duration,
    min_track_length=tcell_min_track_length,
    max_track_length=tcell_max_track_length,
    filter_t0_dead=True,
    cell_type="tcell"
    )
df_tracks_summ = summarize_track_features(
    output_dir=output_dir,
    cell_type="tcell")

--------------- Filtering tracks ---------------
- Plotting tcell touching distribution to D:\SURF_2\Scripts\Python\BEHAV3D3_0\output\analysis\tcell\quality_control\BEHAV3D_tcell_touching_distribution.pdf

D:\SURF_2\Scripts\Python\BEHAV3D3_0\behav3dMA\behav3d\analysis\tcell_analysis.py:204: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_all_tracks_filt=df_all_tracks_filt.groupby(group_cols).apply(lambda group: group.iloc[:max_track_length]).reset_index(drop=True)

- Plotting organoid touching distribution to D:\SURF_2\Scripts\Python\BEHAV3D3_0\output\analysis\tcell\quality_control\BEHAV3D_organoid_touching_distribution.pdf
- Plotting dead dye distribution at all timepoints to D:\SURF_2\Scripts\Python\BEHAV3D3_0\output\analysis\tcell\quality_control\BEHAV3D_dead_dye_distribution.pdf
- Plotting dead dye distribution at timepoint 1 to D:\SURF_2\Scripts\Python\BEHAV3D3_0\output\analysis\tcell\quality_control\BEHAV3D_dead_dye_distribution.pdf
- Plotting track counts after filtering steps to D:\SURF_2\Scripts\Python\BEHAV3D3_0\output\analysis\tcell\quality_control\BEHAV3D_filter_counts.pdf
- Writing filtered tracks to D:\SURF_2\Scripts\Python\BEHAV3D3_0\output\analysis\tcell\track_features\BEHAV3D_tcell_combined_track_features_filtered.csv
### DONE - elapsed time: 0:00:01

--------------- Summarizing track features ---------------
- Writing summarized tracks to D:\SURF_2\Scripts\Python\BEHAV3D3_0\output\analysis\tcell\track_features\BEHAV3D_tcell_combined_track_features_summarized.csv
### DONE - elapsed time: 0:00:00

D:\SURF_2\Scripts\Python\BEHAV3D3_0\behav3dMA\behav3d\utils\analysis.py:79: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.
  ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')
D:\SURF_2\Scripts\Python\BEHAV3D3_0\behav3dMA\behav3d\analysis\tcell_analysis.py:343: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_summarized_tracks['active_tcell_contact'] = grouped_df_tracks.apply(calculate_active_contact_when_contact).reset_index(drop=True)

***Dynamic Time Warping*** <br>

Performs Dynamic Time Warping on the various tracks using various features to calculate a distance matrix between all tracks

Select the features to use for analysis

Features used for dynamic time warping by default:
- z_mean_square_displacement
- z_speed
- z_mean_dead_dye
- tcell_contact
- organoid_contact



*Expected duration: ~1 minute*

In [15]:
import ipywidgets as widgets
from IPython.display import display, clear_output

all_features = [
    'nr_pixels', 'volume', 'bbox_volume', 'extent', 'solidity', 'equivalent_diameter', 
    'major_axis_length', 'minor_axis_length', 'elongation', 'surface_area', 'sphericity',
    'convex_volume', 'orientation_vector', 'mean_intensity_ch1', 'mean_intensity_ch2', 
    'mean_dead_dye', 'mean_intensity_ch4', 'percentage_dead_mask', 'nr_dead_mask_pixels', 
    'increase_dead_mask', 'organoid_contact', 'organoid_contact_pixels', 'touching_organoids',
    'tcell_contact', 'tcell_contact_pixels', 'touching_tcells', 'interpolated', 'displacement',
    'cumulative_displacement', 'displacement_from_origin', 'mean_square_displacement', 'speed',
    'mean_speed', 'dead', 'active_tcell_contact', 'z_mean_square_displacement', 'z_speed', 
    'z_mean_dead_dye'
]

default_selected = {
    "z_mean_square_displacement", 
    "z_speed", 
    "z_mean_dead_dye", 
    "tcell_contact", 
    "organoid_contact"
}

checkboxes = []
for feature in all_features:
    cb = widgets.Checkbox(
        value=(feature in default_selected),
        description=feature,
        indent=False,
        layout=widgets.Layout(width='300px')
    )
    checkboxes.append(cb)

checkboxes_box = widgets.VBox(checkboxes, layout=widgets.Layout(
    overflow='auto',
    height='300px',
    border='1px solid gray',
    padding='5px'
))

save_button = widgets.Button(description="Save DTW Features", button_style='success', layout=widgets.Layout(width='200px'))
output_area = widgets.Output()

def on_save_clicked(b):
    with output_area:
        clear_output()
        global dtw_features
        dtw_features = [cb.description for cb in checkboxes if cb.value]
        print("Selected DTW features:")
        for f in dtw_features:
            print(f"- {f}")

save_button.on_click(on_save_clicked)

display(widgets.Label("Select features to use for Dynamic Time Warping (DTW):"))
display(checkboxes_box)
display(save_button)
display(output_area)

Label(value='Select features to use for Dynamic Time Warping (DTW):')

VBox(children=(Checkbox(value=False, description='nr_pixels', indent=False, layout=Layout(width='300px')), Che…

Button(button_style='success', description='Save DTW Features', layout=Layout(width='200px'), style=ButtonStyl…

Output()

***UMAP fitting and clustering*** <br>

This distance matrix is fitted into a UMAP, and K-means clustering is used to cluster the tracks into clusters

Parameters for UMAP and clustering can be adjusted:
- umap_minimal_distance
- umap_n_neighbors
- nr_of_clusters

***Cluster features display*** <br>

The results of the clustering are displayed in multiple ways:
- The UMAP with clusters and features backprojected onto this UMAP (BEHAV3D_UMAP_clusters.csv)
- A heatmap containing the mean feature values for all tracks per cluster to check general behavior patterns (BEHAV3D_UMAP_cluster_feature_heatmap.pdf)
- A barplot containing the percentages of cells belonging to each cluster per Tcell type (rows) and organoid lines (columns)

In [16]:

# Widgets for UMAP and clustering parameters
umap_distance_widget = widgets.FloatSlider(
    value=0.1, min=0.0, max=1.0, step=0.05, 
    style={'description_width': '64px'}, description='UMAP dist:'
)

umap_neighbors_widget = widgets.IntSlider(
    value=5, min=2, max=50, step=1, 
    style={'description_width': '101px'}, description='UMAP neighbors:'
)

num_clusters_widget = widgets.IntSlider(
    value=6, min=2, max=20, step=1, 
    style={'description_width': '80px'}, description='Num Clusters:'
)

save_button = widgets.Button(description="UMAP&Clustering Params", button_style='success',layout=widgets.Layout(width='250px'))
output_area = widgets.Output()

def on_save_clicked(b):
    with output_area:
        clear_output()
        global umap_minimal_distance, umap_n_neighbors, nr_of_clusters
        umap_minimal_distance = umap_distance_widget.value
        umap_n_neighbors = umap_neighbors_widget.value
        nr_of_clusters = num_clusters_widget.value
        print(f"Saved parameters:\nUMAP distance: {umap_minimal_distance}\nUMAP neighbors: {umap_n_neighbors}\nNumber of clusters: {nr_of_clusters}")

save_button.on_click(on_save_clicked)

display(umap_distance_widget, umap_neighbors_widget, num_clusters_widget)
display(save_button, output_area)

FloatSlider(value=0.1, description='UMAP dist:', max=1.0, step=0.05, style=SliderStyle(description_width='64px…

IntSlider(value=5, description='UMAP neighbors:', max=50, min=2, style=SliderStyle(description_width='101px'))

IntSlider(value=6, description='Num Clusters:', max=20, min=2, style=SliderStyle(description_width='80px'))

Button(button_style='success', description='UMAP&Clustering Params', layout=Layout(width='250px'), style=Butto…

Output()

In [19]:
random.seed(42)  # sets the seed for the random module
df_tracks_clustered = run_tcell_analysis(
    output_dir=output_dir,
    umap_minimal_distance=umap_minimal_distance,
    umap_n_neighbors=umap_n_neighbors,
    nr_of_clusters=nr_of_clusters,
    dtw_features= dtw_features
    )

--------------- Performing T-cell behavioral analysis ---------------
- Calculating the dynamic time warping distance matrix
- Fitting the dynamic time warping to a UMAP

c:\Users\akrashen\Miniforge3\envs\behav3dma\Lib\site-packages\umap\umap_.py:1865: UserWarning: using precomputed metric; inverse_transform will be unavailable
  warn("using precomputed metric; inverse_transform will be unavailable")
c:\Users\akrashen\Miniforge3\envs\behav3dma\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

- Performing clustering on the UMAP data
- Writing clustered tracks to D:\SURF_2\Scripts\Python\BEHAV3D3_0\output\analysis\tcell\results\BEHAV3D_tcell_UMAP_clusters.csv
- Plotting clustered UMAP plots with displayed Track features to D:\SURF_2\Scripts\Python\BEHAV3D3_0\output\analysis\tcell\results\BEHAV3D_tcell_UMAP_clusters.pdf
- Plotting heatmaps with summarized cluster features to D:\SURF_2\Scripts\Python\BEHAV3D3_0\output\analysis\tcell\results\BEHAV3D_tcell_UMAP_cluster_feature_heatmap.pdf

D:\SURF_2\Scripts\Python\BEHAV3D3_0\behav3dMA\behav3d\analysis\tcell_analysis.py:923: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  cluster_means = df_umap[list(info_cols)+["ClusterID"]].drop(columns=sample_cols).groupby('ClusterID').mean().reset_index()

- Plotting percentage plots of each cluster per combination of T-cell and organoid line to D:\SURF_2\Scripts\Python\BEHAV3D3_0\output\analysis\tcell\results\BEHAV3D_tcell_UMAP_cluster_percentages.pdf
MAGE-A4 TCB
- Writing summarized tracks to D:\SURF_2\Scripts\Python\BEHAV3D3_0\output\analysis\tcell\results\BEHAV3D_tcell_UMAP_cluster_percentages.csv
- Writing summarized tracks to D:\SURF_2\Scripts\Python\BEHAV3D3_0\output\analysis\tcell\results\BEHAV3D_tcell_UMAP_cluster_percentages.csv
### DONE - elapsed time: 0:00:05

D:\SURF_2\Scripts\Python\BEHAV3D3_0\behav3dMA\behav3d\analysis\tcell_analysis.py:692: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_clust_perc = df_umap.groupby(["organoid_line", "tcell_line", "ClusterID"]).size().reset_index(name='count')

## Organoid behavioral analysis

**Filtering tracks**

*Expected duration: ~1 minute*

In [ ]:
df_tracks_filt = filter_organoid_tracks(
    metadata=metadata, 
    output_dir=output_dir, 
    exp_duration=exp_duration,
    min_size = 1000,
    cell_type="organoid"
    )

***Death Dynamics*** <br>

In [ ]:
df_tracks_clustered = run_organoid_analysis(
    output_dir=output_dir,
    dead_perc_threshold=0.05
    )

---

# Backproject results

---

**Visualize the cluster IDs and other features over the segments**
 <br>
 
*Duration: <15 minutes*

In [ ]:
print("Samples in metadata .csv:")
for sample_name in metadata["sample_name"]:
    print(sample_name)

In [ ]:
sample_to_backproject="ROCHE_JM1_Exp016-1_Img02_MAGEA4_TCB_Behav3d(4)"

backprojection_data = backproject_mean_features_behav3d(
    sample_name=sample_to_backproject,
    metadata=metadata,
    output_dir=output_dir,
    save=False
)